config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :residents

  post 'subscribe', to: 'home#subscribe'
  get 'thank_you', to: 'home#thank_you'

  root :to => "home#index"
end

app/models/resident.rb
# == Schema Information
#
# Table name: residents
#
#  id            :integer          not null, primary key
#  house_number  :integer
#  road          :string(255)
#  email_address :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

ROADS = [ "Fairfield Road", "Cranworth Road", "Conifer Close" ]

class Resident < ActiveRecord::Base
  validates :house_number, :road, :email_address, presence: true
  validates :email_address, uniqueness: true

  def subscribe(list_id)
    gb = Gibbon::Request.new
    gb.lists(list_id).members.create(body: {email_address: self.email_address, status: "subscribed", double_optin: true})
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default("")
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  invitation_token       :string(255)
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string(255)
#  invitations_count      :integer          default(0)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    return root_path if user.nil?
    residents_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @resident = Resident.new
  end

  def subscribe
    @resident = Resident.new(resident_params)
    if @resident.save
      begin
        @resident.subscribe ENV['MAILCHIMP_LIST_ID']
        redirect_to thank_you_path
      rescue Gibbon::MailChimpError => e
        redirect_to root_path, :flash => { error: e.message }
      end
    else
      render "home/index"
    end
  end

  def thank_you
  end

  private

    def resident_params
      params.require(:resident).permit(:house_number, :road, :email_address)
    end
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_resident, only: [:show, :edit, :update, :destroy]

  # GET /residents
  # GET /residents.json
  def index
    @residents = Resident.order(:house_number, :email_address)
    @groups = @residents.group_by { |r| r.road }
  end

  # GET /residents/1
  # GET /residents/1.json
  def show
  end

  # GET /residents/new
  def new
    @resident = Resident.new
  end

  # GET /residents/1/edit
  def edit
  end

  # POST /residents
  # POST /residents.json
  def create
    @resident = Resident.new(resident_params)

    respond_to do |format|
      if @resident.save
        format.html { redirect_to residents_path notice: 'Resident was successfully created.' }
        format.json { render :show, status: :created, location: @resident }
      else
        format.html { render :new }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residents/1
  # PATCH/PUT /residents/1.json
  def update
    respond_to do |format|
      if @resident.update(resident_params)
        format.html { redirect_to residents_path, notice: 'Resident was successfully updated.' }
        format.json { render :show, status: :ok, location: @resident }
      else
        format.html { render :edit }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residents/1
  # DELETE /residents/1.json
  def destroy
    @resident.destroy
    respond_to do |format|
      format.html { redirect_to residents_url, notice: 'Resident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resident
      @resident = Resident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resident_params
      params.require(:resident).permit(:house_number, :road, :email_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-danger"
    when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/home/index.html.haml
.jumbotron
  .container
    %h1 Street Party 2016!
    %p The legendary Fairfield Road street party is back!
    %p
      Keep your diaries free on
      = succeed '.' do
        %strong Saturday, 17th September 2016
    %p More details to follow.
    %p Enter your house number, road and email address below if you'd like to keep updated via the email newsletter.
    = simple_form_for @resident, url: subscribe_path, class: 'form-inline', wrapper: :inline_form, html: { class: 'form-inline' } do |f|
      = f.input :house_number, :placeholder => "House No."
      = f.input :road, collection: ROADS, selected: ROADS[0]
      = f.input :email_address, :placeholder => "Email Address"
      = f.button :submit, "Subscribe", class: 'btn btn-success'
.container
  %br
  %p.sponsor
    With thanks to
    = link_to 'Belgarum Estate Agents', 'http://www.belgarum.com'
    for their generous sponsorship.
  = link_to image_tag('belgarum.png'), 'http://www.belgarum.com'
  %br

app/views/home/thank_you.html.haml
.jumbotron
  .container
    %h1 Thank you!
.container
  %p Your details have been saved, and we have sent you an email. Please click on the link in the email to confirm your email address.
  %br
  %br
  %br
  %br

app/views/layouts/_messages.html.haml
- if !flash.empty?
  .container
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => flash_class(name) }
          %a.close{"data-dismiss" => "alert"} ×
          = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%header.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      - if user_signed_in?
        = link_to 'Fairfield Road, Winchester', residents_path, class: 'navbar-brand'
      - else
        = link_to 'Fairfield Road, Winchester', root_path, class: 'navbar-brand'
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to 'Edit account', edit_user_registration_path
          %li
            = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
        - else
          %li
            = link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fairfield Road
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    = yield
    .container
      %footer
        %p © Fairfield Road, Winchester, United Kingdom 2014

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title Fairfield Road
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    = yield
    %footer.footer
      .container
        %p= "© Fairfield Road, Winchester, United Kingdom #{Time.now.year}"

app/views/residents/_form.html.haml
= simple_form_for @resident do |f|
  = f.error_notification
  = f.input :house_number
  = f.input :road
  = f.input :email_address
  = f.button :submit, 'Save'

app/views/residents/edit.html.haml
%h1 Editing resident

= render 'form'

= link_to 'Show', @resident
\|
= link_to 'Back', residents_path

app/views/residents/index.html.haml
.page-header
  %h1 Residents
  .actions
    = link_to 'New Resident', new_resident_path, class: 'btn btn-primary'

- @groups.each do |road, residents|
  %h2= road
  %table.table.table-condensed.table-striped.table-hover
    %thead
      %tr
        %th House number
        %th Email address
        %th
        %th
        %th

    %tbody
      - residents.each do |resident|
        %tr
          %td= resident.house_number
          %td= resident.email_address
          %td= link_to 'Show', resident
          %td= link_to 'Edit', edit_resident_path(resident)
          %td= link_to 'Destroy', resident, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/residents/new.html.haml
%h1 New resident

= render 'form'

= link_to 'Back', residents_path

app/views/residents/show.html.haml
%p#notice= notice
.page-header
  %h1 Resident

%form.form-horizontal
  .form-group
    %label.col-sm-2.control-label House No
    .col-sm-10
      %p.form-control-static= @resident.house_number
  .form-group
    %label.col-sm-2.control-label Road
    .col-sm-10
      %p.form-control-static= @resident.road
  .form-group
    %label.col-sm-2.control-label Email Address
    .col-sm-10
      %p.form-control-static= @resident.email_address
  .form-group
    .col-sm-offset-2.col-sm-10
      = link_to 'Edit', edit_resident_path(@resident), class: 'btn btn-primary'
      = link_to 'Back', residents_path